version: "3"

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "admin123!"
      MYSQL_DATABASE: "financialdb"
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
