name: Build dockerfile
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        if: success()
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: docker build
        if: success()
        run: docker build --build-arg SONAR_TOKEN=$SONAR_TOKEN -t murilosrg/financial-api .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: docker push
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push murilosrg/financial-api
