name: Build dockerfile
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: docker login
        if: success()
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        
      - name: docker build
        if: success()
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: docker build -t murilosrg/financial-api .

      - name: docker push
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push murilosrg/financial-api
